cp production/ap90.babylon ../stardict-sanskrit/sa-head/en-entries/apte-1890/apte-1890.babylon
cp production/acc.babylon ../stardict-sanskrit/sa-head/en-entries/aufrecht-catalogus-catalogorum/aufrecht-catalogus-catalogorum.babylon
cp production/ben.babylon ../stardict-sanskrit/sa-head/en-entries/benfey/ben.babylon
cp production/cae.babylon ../stardict-sanskrit/sa-head/en-entries/capeller-sanskrit-english/capeller-sanskrit-english.babylon
cp production/bhs.babylon ../stardict-sanskrit/sa-head/en-entries/edgerton-buddhist-hybrid/edgerton-buddhist-hybrid.babylon
cp production/gst.babylon ../stardict-sanskrit/sa-head/en-entries/goldstucker/goldstucker.babylon
cp production/ieg.babylon ../stardict-sanskrit/sa-head/en-entries/indian-epigraphical-glossary/indian-epigraphical-glossary.babylon
cp production/md.babylon ../stardict-sanskrit/sa-head/en-entries/macdonell/macdonell.babylon
cp production/snp.babylon ../stardict-sanskrit/sa-head/en-entries/Meulenbeld-Sanskrit-Names-of-Plants/Meulenbeld-Sanskrit-Names-of-Plants.babylon
cp production/md.babylon ../stardict-sanskrit/sa-head/en-entries/macdonell/macdonell.babylon
cp production/mw72.babylon ../stardict-sanskrit/sa-head/en-entries/mw-1872/mw-1872.babylon
cp production/pgn.babylon ../stardict-sanskrit/sa-head/en-entries/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions.babylon
cp production/shs.babylon ../stardict-sanskrit/sa-head/en-entries/shabda-sAgara/shabda-sAgara.babylon
cp production/vei.babylon ../stardict-sanskrit/sa-head/en-entries/Vedic-Index-of-Names-and-Subjects/Vedic-Index-of-Names-and-Subjects.babylon
cp production/wil.babylon ../stardict-sanskrit/sa-head/en-entries/wilson/wilson.babylon
cp production/yat.babylon ../stardict-sanskrit/sa-head/en-entries/yates/yates.babylon
cp production/bop.babylon ../stardict-sanskrit/sa-head/other-entries/bopp/bopp.babylon
cp production/bur.babylon ../stardict-sanskrit/sa-head/french-entries/burnouf/burnouf.babylon
cp production/stc.babylon ../stardict-sanskrit/sa-head/french-entries/Stchoupak-Sanscrit-French/Stchoupak-Sanscrit-French.babylon
cp production/pwg.babylon ../stardict-sanskrit/sa-head/german-entries/Bohtlingk-and-Roth-Grosses-Petersburger-Worterbuch/Bohtlingk-and-Roth-Grosses-Petersburger-Worterbuch.babylon
cp production/pw.babylon ../stardict-sanskrit/sa-head/german-entries/Bohtlingk-Sanskrit-Worterbuch-in-kurzerer-Fassung/Bohtlingk-Sanskrit-Worterbuch-in-kurzerer-Fassung.babylon
cp production/ccs.babylon ../stardict-sanskrit/sa-head/german-entries/capeller-sanskrit-german/capeller-sanskrit-german.babylon
cp production/sch.babylon ../stardict-sanskrit/sa-head/german-entries/Schmidt-Nachtrage-zum-Sanskrit-Worterbuch/Schmidt-Nachtrage-zum-Sanskrit-Worterbuch.babylon
cp production/gra.babylon ../stardict-sanskrit/sa-head/german-entries/grassman-sanskrit-german/grassman-sanskrit-german.babylon
cp production/skd.babylon ../stardict-sanskrit/sa-head/sa-entries/kalpadruma-sa/kalpadruma-sa.babylon
cp production/vcp.babylon ../stardict-sanskrit/sa-head/sa-entries/vAchaspatyam-sa/vAchaspatyam-sa.babylon
cp production/bor.babylon ../stardict-sanskrit/en-head/borooah/borooah.babylon
cp production/mwe.babylon ../stardict-sanskrit/en-head/mw-english-sanskrit/mw-english-sanskrit.babylon
