cp production/ap90.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/apte-1890/apte-1890.babylon
cp production/acc.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/aufrecht-catalogus-catalogorum/aufrecht-catalogus-catalogorum.babylon
cp production/ben.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/benfey/benfey.babylon
cp production/cae.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/capeller-sanskrit-english/capeller-sanskrit-english.babylon
cp production/bhs.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/edgerton-buddhist-hybrid/edgerton-buddhist-hybrid.babylon
cp production/gst.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/goldstucker/goldstucker.babylon
cp production/ieg.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/indian-epigraphical-glossary/indian-epigraphical-glossary.babylon
cp production/lan.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/lanman/lanman.babylon
cp production/md.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/macdonell/macdonell.babylon
cp production/snp.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/Meulenbeld-Sanskrit-Names-of-Plants/Meulenbeld-Sanskrit-Names-of-Plants.babylon
cp production/mw72.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/mw-1872/mw-1872.babylon
cp production/mw.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/mw-cologne/mw-cologne.babylon
cp production/pgn.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions.babylon
cp production/shs.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/shabda-sAgara/shabda-sAgara.babylon
cp production/vei.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/Vedic-Index-of-Names-and-Subjects/Vedic-Index-of-Names-and-Subjects.babylon
cp production/wil.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/wilson/wilson.babylon
cp production/yat.babylon ../../indic-dict/stardict-sanskrit/sa-head/en-entries/yates/yates.babylon
cp production/bop.babylon ../../indic-dict/stardict-sanskrit/sa-head/other-entries/bopp/bopp.babylon
cp production/bur.babylon ../../indic-dict/stardict-sanskrit/sa-head/french-entries/burnouf/burnouf.babylon
cp production/stc.babylon ../../indic-dict/stardict-sanskrit/sa-head/french-entries/Stchoupak-Sanscrit-French/Stchoupak-Sanscrit-French.babylon
cp production/pwg.babylon ../../indic-dict/stardict-sanskrit/sa-head/german-entries/Bohtlingk-and-Roth-Grosses-Petersburger-Worterbuch/Bohtlingk-and-Roth-Grosses-Petersburger-Worterbuch.babylon
cp production/pw.babylon ../../indic-dict/stardict-sanskrit/sa-head/german-entries/Bohtlingk-Sanskrit-Worterbuch-in-kurzerer-Fassung/Bohtlingk-Sanskrit-Worterbuch-in-kurzerer-Fassung.babylon
cp production/ccs.babylon ../../indic-dict/stardict-sanskrit/sa-head/german-entries/capeller-sanskrit-german/capeller-sanskrit-german.babylon
cp production/sch.babylon ../../indic-dict/stardict-sanskrit/sa-head/german-entries/Schmidt-Nachtrage-zum-Sanskrit-Worterbuch/Schmidt-Nachtrage-zum-Sanskrit-Worterbuch.babylon
cp production/gra.babylon ../../indic-dict/stardict-sanskrit/sa-head/german-entries/grassman-sanskrit-german/grassman-sanskrit-german.babylon
cp production/skd.babylon ../../indic-dict/stardict-sanskrit/sa-head/sa-entries/kalpadruma-sa/kalpadruma-sa.babylon
cp production/vcp.babylon ../../indic-dict/stardict-sanskrit/sa-head/sa-entries/vAchaspatyam-sa/vAchaspatyam-sa.babylon
cp production/armh.babylon ../../indic-dict/stardict-sanskrit/sa-head/sa-entries/abhidhAnaratnamAlA/abhidhAnaratnamAlA.babylon
cp production/bor.babylon ../../indic-dict/stardict-sanskrit/en-head/borooah/borooah.babylon
cp production/mwe.babylon ../../indic-dict/stardict-sanskrit/en-head/mw-english-sanskrit/mw-english-sanskrit.babylon
cp production/ae.babylon ../../indic-dict/stardict-sanskrit/en-head/apte-english-sanskrit-cologne/apte-english-sanskrit-cologne.babylon

