name: Generate Babylon Dictionary

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          production/snp.babylon
        sparse-checkout-cone-mode: false
    
    - name: Install stardict-tools
      run: |
        sudo apt update
        sudo apt install -y stardict-tools
    
    - name: Test babylon file
      run: |
        /usr/lib/stardict-tools/babylon production/snp.babylon stardict/
    
    - name: Show stardict folder contents
      run: |
        ls -la stardict/