name: Generate Babylon Dictionary

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download babylon file
      run: |
        mkdir -p production stardict
        curl -o production/snp.babylon https://raw.githubusercontent.com/sanskrit-lexicon/cologne-stardict/refs/heads/master/production/snp.babylon
    
    - name: Install stardict-tools
      run: |
        sudo apt install -y stardict-tools
    
    - name: Test babylon file
      run: |
        /usr/lib/stardict-tools/babylon production/snp.babylon stardict/
    
    - name: Show stardict folder contents
      run: |
        ls -la stardict/
        cat stardict/stardict.ifo
        