name: Generate Babylon Dictionary

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download babylon file
      run: |
        mkdir -p production stardict
        curl -o production/snp.babylon https://raw.githubusercontent.com/sanskrit-lexicon/cologne-stardict/refs/heads/master/production/snp.babylon
    
    - name: Install pyglossary
      run: |
        pip install pyglossary lxml
    
    - name: Convert babylon to stardict
      run: |
        pyglossary --read-format=BGL production/snp.babylon stardict/snp.ifo
    
    - name: Show stardict folder contents
      run: |
        ls -la stardict/
        cat stardict/stardict.ifo
        